---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	reader(reader)
	klassifikation(klassifikation)
	klassifikation_klaerfall(klassifikation_klaerfall)
	extraktion_zahlung(extraktion_zahlung)
	abgleich(abgleich)
	buchung(buchung)
	klaerfall(klaerfall)
	extraktion_rechnung(extraktion_rechnung)
	rechnungsextraktion_klaerfall(rechnungsextraktion_klaerfall)
	kostenstelle(kostenstelle)
	freigabe_kostenstelle(freigabe_kostenstelle)
	elo(elo)
	__end__([<p>__end__</p>]):::last
	__start__ --> reader;
	abgleich -.-> buchung;
	abgleich -. &nbsp;hitl&nbsp; .-> klaerfall;
	buchung -. &nbsp;ende&nbsp; .-> __end__;
	buchung -. &nbsp;hitl&nbsp; .-> klaerfall;
	extraktion_rechnung -. &nbsp;ende&nbsp; .-> __end__;
	extraktion_rechnung -.-> kostenstelle;
	extraktion_rechnung -. &nbsp;review&nbsp; .-> rechnungsextraktion_klaerfall;
	extraktion_zahlung -. &nbsp;ende&nbsp; .-> __end__;
	extraktion_zahlung -.-> abgleich;
	freigabe_kostenstelle -. &nbsp;ende&nbsp; .-> __end__;
	freigabe_kostenstelle -.-> elo;
	klaerfall -. &nbsp;ende&nbsp; .-> __end__;
	klaerfall -.-> buchung;
	klaerfall -.-> kostenstelle;
	klassifikation -. &nbsp;ende&nbsp; .-> __end__;
	klassifikation -. &nbsp;prozess_b&nbsp; .-> extraktion_rechnung;
	klassifikation -. &nbsp;prozess_a&nbsp; .-> extraktion_zahlung;
	klassifikation -. &nbsp;review&nbsp; .-> klassifikation_klaerfall;
	klassifikation_klaerfall -. &nbsp;ende&nbsp; .-> __end__;
	klassifikation_klaerfall -. &nbsp;prozess_b&nbsp; .-> extraktion_rechnung;
	klassifikation_klaerfall -. &nbsp;prozess_a&nbsp; .-> extraktion_zahlung;
	kostenstelle -.-> elo;
	kostenstelle -. &nbsp;freigabe&nbsp; .-> freigabe_kostenstelle;
	reader -. &nbsp;ende&nbsp; .-> __end__;
	reader -.-> klassifikation;
	rechnungsextraktion_klaerfall -. &nbsp;ende&nbsp; .-> __end__;
	rechnungsextraktion_klaerfall -.-> kostenstelle;
	elo --> __end__;
	freigabe_kostenstelle -. &nbsp;freigabe&nbsp; .-> freigabe_kostenstelle;
	klaerfall -. &nbsp;hitl&nbsp; .-> klaerfall;
	klassifikation_klaerfall -. &nbsp;review&nbsp; .-> klassifikation_klaerfall;
	rechnungsextraktion_klaerfall -. &nbsp;review&nbsp; .-> rechnungsextraktion_klaerfall;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
